### PR TITLE
Style for Food Blog

### PR DESCRIPTION
**Pull request by kivenalaric**
addition of styles for food blog

### CODE REVIEW

**Review by nganifaith — CHANGES_REQUESTED** [review]
@kivenalaric Great job so far.

- [ ] Follow the formate of readme provided. Add pictures and links where necessary.

**Review by nganifaith — CHANGES_REQUESTED** [review]
@kivenalaric Great job so far. We have some little fixes to do.

**_Responsiveness_**

- [ ] images are not responsive. Refer to images below.
Screen Shot 2022-11-10 at 10 52 22
**Original design on mobile**
Screen Shot 2022-11-10 at 10 52 07

**Yours**

- [ ] See footer section. 
Screen Shot 2022-11-10 at 10 11 59

Screen Shot 2022-11-10 at 10 53 08

**Review by nganifaith — CHANGES_REQUESTED** [review]
@kivenalaric great effort implementing the changes, however still missing some details.

- [ ] image responsiveness still not the best. Refer to the images below. 
Screen Shot 2022-11-11 at 12 23 41

Screen Shot 2022-11-11 at 12 23 28

**Comment by nganifaith** [comment]
@kivenalaric too much wild space image mobile view

**Comment by kivenalaric** [comment]
> @kivenalaric too much wild space image mobile view

Ive made adjustments on the image responsiveness

**Comment by nganifaith** [comment]
@kivenalaric congrats. Go ahead and merge your work

**Pull request merged**
